"""Documented figures must match the run that produced them.

Hand-copied numbers drift. This repo shipped a requirements-mapping row quoting
a p95 twenty times lower than the latency table forty lines below it, both
supposedly from the same run -- a contradiction a reader finds in a minute.

Every drift-prone figure in README.md and docs/DEMO_SCRIPT.md is now wrapped in
a <!--m:name--> marker and generated by scripts/sync_docs.py from
data/metrics.json. This test fails the build when they diverge.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
METRICS = ROOT / "docs" / "reference_metrics.json"
SYNC = ROOT / "scripts" / "sync_docs.py"
DOCS = [ROOT / "README.md", ROOT / "docs" / "DEMO_SCRIPT.md"]
MARKER = re.compile(r"<!--m:([a-z0-9_]+)-->(.*?)<!--/m-->", re.S)


def test_docs_match_the_last_run():
    assert METRICS.exists(), "the committed reference metrics snapshot is missing"
    r = subprocess.run([sys.executable, str(SYNC), "--check"],
                       capture_output=True, text=True, cwd=ROOT)
    assert r.returncode == 0, f"documented figures are stale:\n{r.stdout}{r.stderr}"


def test_every_marker_resolves_to_a_known_metric():
    sys.path.insert(0, str(ROOT / "scripts"))
    from sync_docs import values  # noqa: E402

    known = set(values(json.loads(METRICS.read_text())))
    unknown = {name for doc in DOCS for name, _ in MARKER.findall(doc.read_text())
               if name not in known}
    assert not unknown, f"docs reference metrics that sync_docs cannot supply: {unknown}"


def test_no_bare_stale_figures_remain():
    """The specific contradictions the review found must not reappear."""
    readme = (ROOT / "README.md").read_text()
    for stale in ("p95 6.0 ms, 98% within budget", "31% invocation rate"):
        assert stale not in readme, f"stale figure back in README: {stale!r}"


def test_markers_are_invisible_in_rendered_markdown():
    """Markers must be HTML comments so they render as nothing."""
    for doc in DOCS:
        for mo in MARKER.finditer(doc.read_text()):
            assert mo.group(0).startswith("<!--") and mo.group(0).endswith("-->")
            assert "\n" not in mo.group(2), "marker value must stay on one line"
